import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#111319",
        surface: "#111319",
        "surface-dim": "#111319",
        "surface-container-lowest": "#0c0e13",
        "surface-container-low": "#191c21",
        "surface-container": "#1d2025",
        "surface-container-high": "#282a30",
        "surface-container-highest": "#33353b",
        "surface-variant": "#33353b",
        "surface-bright": "#37393f",
        "on-background": "#e2e2ea",
        "on-surface": "#e2e2ea",
        "on-surface-variant": "#c4c9ac",
        outline: "#8e9379",
        "outline-variant": "#444933",
        primary: "#c3f400",
        "primary-fixed": "#c3f400",
        "primary-fixed-dim": "#abd600",
        "primary-container": "#c3f400",
        "on-primary-fixed": "#161e00",
        "on-primary-container": "#556d00",
        "surface-tint": "#abd600",
        secondary: "#d3fbff",
        "secondary-fixed": "#7df4ff",
        "secondary-container": "#00eefc",
        "on-secondary-container": "#00686f",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        sans: ["var(--font-geist)", "Geist", "Inter", "sans-serif"],
        display: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "display-hero": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-lg": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-md": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "label-mono-lg": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "label-mono-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "label-mono-xs": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        gutter: "1.25rem",
        "gutter-lg": "1.75rem",
        margin: "1.5rem",
        "margin-lg": "3rem",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
